### ISSUE TITLE
Merge sort in C++ 

### ISSUE THREAD

**Issue by HimangsKalita** [CodeChefMUST/DSA#43]

**Comment by priyanshi2808** [comment]
I would like to work on this issue @HimangsKalita .please assign it to me.

**Comment by Taneesha-creates** [comment]
Hello @HimangsKalita , this issue has been assigned to you.

# Important:

Before you start your work on this issue, **make sure** you go through the README.md and Contribution Guidelines.md

## File structure:
1. Go to the Sorting Directory
2. If a folder "Merge Sort" does not already exist, please create the sub directory in the "Sorting" directory.
3. Since your implementation will be in C++, create another sub directory within `Merge Sort` named `C++`.
4. In the C++ directory, you can write the code, and name the file `MergeSort.cpp`.

Here's how the final structure should look like:
- Sorting
    - Merge Sort
        - Algorithm.md
        - C++
            - MergeSort.cpp

### Please follow the *same* naming conventions as mentioned in this comment.

## Before you create a pull request, if you observe that the folder Merge Sort has already been created, or the C++ sub directory has already been created, then please refrain from creating a new one, make some changes in your forked repository so that it matches with the current one and there are no conflicts. (pull it, change your file location to be as mentioned in this comment)

We thank you for your contribution and time and we hope that you enjoy contributing to open source.

**Comment by Taneesha-creates** [comment]
Hi, @priyanshi2808, we appreciate your interest in contributing to this issue. However, this repository follows a strict first come first served basis and the issue has hence been assigned to @HimangsKalita.

You can look through the rest of our issues, find one that has not been assigned, or create another! We hope you enjoy contributing to open source :)
