### ISSUE TITLE
bubble sort code in Sorting/Bubble Sort/C++

### ISSUE THREAD

**Issue by deepansha-singh** [CodeChefMUST/DSA#8]

**Comment by aditiaher** [comment]
I can work on this please assign it to me.

**Comment by 22tanyabansal** [comment]
I want to work on this issue please assign to me @deepansha-singh

**Comment by deepansha-singh** [comment]
@22tanyabansal 
I have asked the repo manager concerned with merging PRs to look into it. We appreciate your patience :)

**Comment by Taneesha-creates** [comment]
Hello @22tanyabansal, we noticed that it has been 5 days since the issue was assigned to you, and we'd like to bring to your notice that you are required to submit a pull request within 7 days of being assigned the issue as per the guidelines, and you now have 2 days remaining.

# Important

Here are the guidelines for the code, for your reference:
1. In the `Sorting` directory, navigate to `Bubble Sort`
2. Create a sub directory within Bubble Sort, with the name `C++`
3. In this C++ directory, write the file `BubbleSort.cpp` containing the source code.

### Please follow the *same* naming conventions as mentioned in this comment.

## Before you create a pull request, if you observe that the required folders have already been created, then please refrain from creating a new one, make some changes in your forked repository so that it matches with the current one and there are no conflicts.

## Note that all PRs are being checked for plagiarism, please refrain from indulging in any crooked means, we trust you!

We thank you for your contribution and time and we hope that you enjoy contributing to open source.

**Comment by 22tanyabansal** [comment]
I already submit my PR any you merged it 5 days ago @Taneesha-creates

**Comment by Taneesha-creates** [comment]
@22tanyabansal, I do not see the code in the repo. Can you create a pull request again? Sorry for the inconvenience!
